[platformio]
default_envs = controller, rear_display
src_dir = src
test_dir = test

[env:_esp32_base]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
    -std=gnu++17
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
build_unflags = -std=gnu++11
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.partitions = default_16MB.csv

[env:controller]
extends = env:_esp32_base
build_src_filter =
    +<controller/>
    -<rear_display/>
board_upload.flash_size = 16MB
lib_deps =
    lvgl/lvgl@8.4.0
build_flags =
    ${env:_esp32_base.build_flags}
    -Iinclude
    -DLV_CONF_INCLUDE_SIMPLE
    -DROAD_ROASTER_CONTROLLER

[env:rear_display]
extends = env:_esp32_base
build_src_filter =
    -<controller/>
    +<rear_display/>
board_upload.flash_size = 32MB
lib_deps =
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@3.0.15
    adafruit/Adafruit GFX Library@1.12.3
build_flags =
    ${env:_esp32_base.build_flags}
    -DROAD_ROASTER_REAR_DISPLAY

[env:native]
platform = native
test_framework = unity
build_src_filter =
    -<controller/>
    -<rear_display/>
build_flags =
    -std=gnu++17
    -DROAD_ROASTER_NATIVE_TEST
