#!/usr/bin/env python3
"""Convert Spleen BDF pixel fonts to fixed Adafruit GFX strikes."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "tools/fonts/spleen"
OUTPUT_PATH = ROOT / "src/rear_display/spleen_bitmaps.hpp"
FONT_SIZES = ((16, 32), (12, 24), (8, 16), (6, 12))
FIRST_CODEPOINT = 0x20
LAST_CODEPOINT = 0xFF


@dataclass(frozen=True)
class BdfGlyph:
    width: int
    height: int
    x_advance: int
    x_offset: int
    y_offset: int
    rows: tuple[str, ...]


def parse_bdf(path: Path) -> tuple[dict[int, BdfGlyph], int]:
    glyphs: dict[int, BdfGlyph] = {}
    lines = path.read_text(encoding="ascii").splitlines()
    y_advance = 0
    index = 0

    while index < len(lines):
        line = lines[index]
        if line.startswith("FONTBOUNDINGBOX "):
            y_advance = int(line.split()[2])
        if line != "STARTCHAR SPACE" and not line.startswith("STARTCHAR "):
            index += 1
            continue

        encoding = -1
        x_advance = 0
        width = height = x_offset = bdf_y_offset = 0
        rows: list[str] = []
        index += 1
        while index < len(lines) and lines[index] != "ENDCHAR":
            field = lines[index]
            if field.startswith("ENCODING "):
                encoding = int(field.split()[1])
            elif field.startswith("DWIDTH "):
                x_advance = int(field.split()[1])
            elif field.startswith("BBX "):
                _, w, h, x, y = field.split()
                width, height = int(w), int(h)
                x_offset, bdf_y_offset = int(x), int(y)
            elif field == "BITMAP":
                rows = lines[index + 1 : index + 1 + height]
                index += height
            index += 1

        if encoding >= 0:
            # BDF y is the glyph bottom relative to the baseline; GFX y is the
            # glyph top relative to it.
            glyphs[encoding] = BdfGlyph(
                width,
                height,
                x_advance,
                x_offset,
                -(height + bdf_y_offset),
                tuple(rows),
            )
        index += 1

    if y_advance == 0:
        raise ValueError(f"FONTBOUNDINGBOX missing from {path}")
    return glyphs, y_advance


def pack_glyph(glyph: BdfGlyph) -> list[int]:
    bits: list[int] = []
    for row in glyph.rows:
        row_value = int(row, 16)
        padded_width = len(row) * 4
        bits.extend(
            (row_value >> (padded_width - bit - 1)) & 1
            for bit in range(glyph.width)
        )

    packed: list[int] = []
    for start in range(0, len(bits), 8):
        byte = 0
        chunk = bits[start : start + 8]
        for bit in chunk:
            byte = (byte << 1) | bit
        packed.append(byte << (8 - len(chunk)))
    return packed


def format_bytes(values: list[int], indent: str = "    ") -> list[str]:
    lines: list[str] = []
    for start in range(0, len(values), 16):
        chunk = values[start : start + 16]
        lines.append(indent + "".join(f"0x{value:02X}, " for value in chunk))
    return lines or [indent + "0x00,"]


def generate_strike(path: Path) -> tuple[list[int], list[tuple[int, ...]], int]:
    source, y_advance = parse_bdf(path)
    required = (*range(0x20, 0x7F), *range(0xA0, 0x100))
    missing = [codepoint for codepoint in required if codepoint not in source]
    if missing:
        formatted = ", ".join(f"U+{codepoint:04X}" for codepoint in missing)
        raise ValueError(f"{path.name} is missing required glyphs: {formatted}")
    fallback = source[ord("?")]
    bitmap: list[int] = []
    glyphs: list[tuple[int, ...]] = []

    for codepoint in range(FIRST_CODEPOINT, LAST_CODEPOINT + 1):
        # U+0080..U+009F are non-printing C1 controls, but GFXfont requires a
        # contiguous table. Their slots deliberately use the question mark.
        glyph = source.get(codepoint, fallback)
        offset = len(bitmap)
        bitmap.extend(pack_glyph(glyph))
        glyphs.append(
            (
                offset,
                glyph.width,
                glyph.height,
                glyph.x_advance,
                glyph.x_offset,
                glyph.y_offset,
            )
        )
    return bitmap, glyphs, y_advance


def main() -> None:
    output = [
        "// Generated by tools/generate_matrix_fonts.py. Do not edit manually.",
        "// Source: Spleen 2.2.0, BSD 2-Clause License.",
        "#pragma once",
        "",
        "#include <Adafruit_GFX.h>",
        "",
        "namespace rr::rear::matrix_font {",
        "",
    ]
    strike_names: list[str] = []

    for width, height in FONT_SIZES:
        stem = f"Spleen{width}x{height}"
        strike_names.append(stem)
        bitmap, glyphs, y_advance = generate_strike(
            FONT_DIR / f"spleen-{width}x{height}.bdf"
        )
        output.append(f"inline const uint8_t {stem}Bitmaps[] PROGMEM = {{")
        output.extend(format_bytes(bitmap))
        output.extend(("};", ""))
        output.append(f"inline const GFXglyph {stem}Glyphs[] PROGMEM = {{")
        for offset, glyph_width, glyph_height, advance, x_offset, y_offset in glyphs:
            output.append(
                f"    {{{offset}, {glyph_width}, {glyph_height}, {advance}, "
                f"{x_offset}, {y_offset}}},"
            )
        output.extend(("};", ""))
        output.extend(
            (
                f"inline const GFXfont {stem} PROGMEM = {{",
                f"    (uint8_t*){stem}Bitmaps,",
                f"    (GFXglyph*){stem}Glyphs,",
                f"    0x{FIRST_CODEPOINT:02X}, 0x{LAST_CODEPOINT:02X}, {y_advance}}};",
                "",
            )
        )

    output.append("inline const GFXfont* const kStrikes[] = {")
    output.extend(f"    &{name}," for name in strike_names)
    output.extend(
        (
            "};",
            "inline constexpr size_t kStrikeCount =",
            "    sizeof(kStrikes) / sizeof(kStrikes[0]);",
            "",
            "}  // namespace rr::rear::matrix_font",
            "",
        )
    )
    OUTPUT_PATH.write_text("\n".join(output), encoding="ascii")


if __name__ == "__main__":
    main()
